apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rec-deployment
  namespace: chandana-ns
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: rec
  template:
    metadata:
      labels: 
        app: rec
    spec: 
      containers:
      - name: rec-container
        image: nimeshsv814/recruitment-app:v1.1.1
        ports: 
        - containerPort: 3000
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: recruitment-secr
                key: url

            
 

---
apiVersion: v1
kind: Service
metadata:
  name: rec-service
  namespace: chandana-ns
spec:
  selector:
    app: rec
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort





