version: "3.8"

services:
  frontend:
    image: chandu554/recruitment:v1.1.0
    container_name: Recruitment-app1
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://backend:27017/AFF-Docker
    depends_on:
      - backend
    networks:
      - frontend-net

  backend:
    image: mongo
    container_name: mongodb-cont1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-net

  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
